name: myplugin
version: '1.0-SNAPSHOT'
main: me.hysun.myplugin.Myplugin
api-version: '1.21'
authors: [ hysun ]
description: my first plugin
commands:
  setspawn:
    description: set spawn location
  spawn:
    description: teleport to spawn
  joinmessage:
    description: sets the join message
  god:
    description: toggle god mode
  fly:
    description: toggle flying
  nick:
    description: set nickname
  vanish:
    description: toggle invisibility
  sethome:
    description: set home
  home:
    description: teleport to home
  enderchest:
    description: opens player enderchest
  inv:
    description: opens player inv